"""
TTS (Text-to-Speech) Router
Handles text-to-speech synthesis using Supertonic 3
"""

from typing import Any, Optional
from fastapi import APIRouter, Form, HTTPException
from fastapi.responses import Response

from app.models.tts import (
    TTSModelsResponse,
    TTSVoicesResponse,
)
from app.services.tts_service import (
    DEFAULT_TTS_VOICE,
    DEFAULT_TTS_MODEL,
    tts_cache,
    process_tts,
    get_available_models,
    get_available_voices,
    persist_tts_cache,
)


# Router instance
router = APIRouter(prefix="/api/v1/tts", tags=["tts"])


@router.get("/models", response_model=TTSModelsResponse)
async def list_tts_models() -> TTSModelsResponse:
    """List available TTS models"""
    return TTSModelsResponse(
        models=get_available_models(), default_model=DEFAULT_TTS_MODEL
    )


@router.get("/voices", response_model=TTSVoicesResponse)
async def list_voices() -> TTSVoicesResponse:
    """List available voice options"""
    return TTSVoicesResponse(
        voices=get_available_voices(), default_voice=DEFAULT_TTS_VOICE
    )


@router.get("/synthesize")
async def synthesize_tts_info() -> dict[str, Any]:
    """Return usage information for the POST-only audio synthesis operation."""
    return {
        "detail": "Use POST multipart/form-data to synthesize audio.",
        "method": "POST",
        "required_fields": ["text"],
        "optional_fields": [
            "model",
            "voice",
            "speed",
            "pitch",
            "language",
            "instruction",
            "output_format",
        ],
        "backend": {
            "supertonic": "Install with: pip install -r requirements.txt. The first synthesis run downloads Supertonic 3 assets from Hugging Face.",
        },
        "models_endpoint": "/api/v1/tts/models",
        "voices_endpoint": "/api/v1/tts/voices",
    }


@router.post("/synthesize")
async def synthesize_tts(
    text: str = Form(..., description="Text to synthesize"),
    model: str = Form(DEFAULT_TTS_MODEL, description="TTS model to use"),
    voice: str = Form(
        DEFAULT_TTS_VOICE, description="Supertonic voice preset: M1-M5 or F1-F5"
    ),
    speed: float = Form(1.0, description="Speech speed (0.7-2.0)"),
    pitch: float = Form(1.0, description="Pitch adjustment (0.5-2.0)"),
    language: Optional[str] = Form(
        None, description="Language name, or Auto/empty for auto-detection"
    ),
    instruction: Optional[str] = Form(
        None,
        description="Accepted for compatibility; ignored as a prompt by Supertonic",
    ),
    output_format: str = Form("wav", description="Output format: wav, mp3"),
) -> Response:
    """
    Synthesize speech from text using Supertonic 3.

    Successful responses are generated by real model inference only. If the
    selected backend is not installed or the route cannot support its required
    inputs, the API returns an error instead of mock audio.

    Supported models:
    - Supertone/supertonic-3
    """
    normalized_output_format = (output_format or "wav").lower().strip()
    if normalized_output_format not in {"wav", "mp3"}:
        raise HTTPException(
            status_code=400, detail="output_format must be 'wav' or 'mp3'"
        )

    tts_id, audio_bytes, duration, sample_rate = await process_tts(
        text=text,
        model=model,
        voice=voice,
        speed=speed,
        pitch=pitch,
        language=language,
        instruction=instruction,
        output_format=normalized_output_format,
    )

    # Return audio response
    media_type = "audio/wav" if normalized_output_format == "wav" else "audio/mpeg"
    filename = f"{tts_id}.{normalized_output_format}"

    return Response(
        content=audio_bytes,
        media_type=media_type,
        headers={
            "X-TTS-ID": tts_id,
            "X-Duration": str(duration),
            "X-Sample-Rate": str(sample_rate),
            "Content-Disposition": f'inline; filename="{filename}"',
            "Cache-Control": "no-store",
            "Content-Length": str(len(audio_bytes)),
        },
    )


@router.get("/result/{tts_id}")
async def get_tts_result(tts_id: str) -> Any:
    """Get TTS result metadata by ID"""
    if tts_id not in tts_cache:
        raise HTTPException(status_code=404, detail="TTS result not found")

    return tts_cache[tts_id]


@router.delete("/result/{tts_id}")
async def delete_tts_result(tts_id: str) -> dict[str, str]:
    """Delete a TTS result"""
    if tts_id not in tts_cache:
        raise HTTPException(status_code=404, detail="TTS result not found")

    del tts_cache[tts_id]
    persist_tts_cache()
    return {"message": "TTS result deleted", "id": tts_id}


@router.get("/list")
async def list_tts_results() -> dict[str, Any]:
    """List all TTS results in cache"""
    return {
        "results": [entry.model_dump() for entry in tts_cache.values()],
        "total": len(tts_cache),
    }
